# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-toolkit" do
  name "go-toolkit"
  desc "CLI for Go scaffolding and dependency workflows."
  homepage "https://github.com/louiss0/go-toolkit"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtk"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_darwin_amd64.tar.gz"
      sha256 "e23483ce81c57b5cc5246c933859cba9943a5cd408811fa16fceec6baa3ca04c"
    end
    on_arm do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_darwin_arm64.tar.gz"
      sha256 "ca81cac526ffe997239d144bbc765e3eadb4eec67e69099eb459b83ab8c0f326"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_linux_amd64.tar.gz"
      sha256 "267aa17dde21f306cef39ffdf8a8e131c4a3670df3b89cdee25121ba5c276318"
    end
    on_arm do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_linux_arm64.tar.gz"
      sha256 "749ebdec3ed93edca502ebee440b9d60fe8567a8452bc0012904e11ef75b539b"
    end
  end

  # No zap stanza required
end
