# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-toolkit" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_darwin_amd64.tar.gz"
      sha256 "0105e5746efb110df65ec95b4fc93d0705bc275e858d686b057453f0c1e9592a"
    end
    on_arm do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_darwin_arm64.tar.gz"
      sha256 "cdfd889d9d11d72f27db558c824352833dd5301d3166fa3f880bfd04aaac5f94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_linux_amd64.tar.gz"
      sha256 "70523ac349c4588317f4e57aecabe0756c5a8bfd9a85d01fa017777e9fff9bf8"
    end
    on_arm do
      url "https://github.com/louiss0/go-toolkit/releases/download/v#{version}/go-toolkit_#{version}_linux_arm64.tar.gz"
      sha256 "362f5914cb8cf9c9a4832f933c88d5ddc8ed1f8cd92884d1b4d68c2adf136d58"
    end
  end

  name "go-toolkit"
  desc "CLI for Go scaffolding and dependency workflows."
  homepage "https://github.com/louiss0/go-toolkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gtk"

  # No zap stanza required

end
