# This file was generated by GoReleaser. DO NOT EDIT.
cask "javascript-package-delegator" do
  desc "A tool to delegate package installation to JavaScript package managers."
  homepage "https://github.com/louiss0/javascript-package-delegator"
  version "1.0.1"
  sha256 :no_check

  livecheck do
    strategy :github_latest
  end

  binary "jpd"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_darwin_amd64.tar.gz"
      sha256 "b32a230b968c313463717e2c7d35f5ceb385ccf77ff627e131c7986943da1884"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_darwin_arm64.tar.gz"
      sha256 "e635d6b65d56844ea7cf56d5e4177a81cd336df5c263286eb295e1b124ebea15"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_linux_amd64.tar.gz"
      sha256 "39f832ca85d74b16b2d6651023d822b7ea5595a975f4beaaef2c11e8f82e83cd"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.0.1/javascript-package-delegator_1.0.1_linux_arm64.tar.gz"
      sha256 "9e05c9817e665a06a09e5bf1d3842580908e0d76293af2b2d277392c60c6a723"
    end
  end

  # No zap stanza required
end
