# This file was generated by GoReleaser. DO NOT EDIT.
cask "javascript-package-delegator" do
  desc "A CLI for executing JavaScript package manager commands based on lock files. Supports npm, yarn, pnpm, bun, and deno."
  homepage "https://github.com/louiss0/javascript-package-delegator"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jpd"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_darwin_amd64.tar.gz"
      sha256 "0d72afca836bd01bf655dd077e20cac7f0ba929e9df733b82a05754c2c8dfa4d"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_darwin_arm64.tar.gz"
      sha256 "220c5960fcb45726d87e1a931aa4632484596bb5ca2e4f123a46e83cd40b98d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_linux_amd64.tar.gz"
      sha256 "c29cc9ed16a41e9bf02234b949f1bdd5abebf1f22d729d1ca7e30375fbe92ef5"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.2.0/javascript-package-delegator_1.2.0_linux_arm64.tar.gz"
      sha256 "905e4f79b2155710015e5ec987b0242616d0ca1cf7ca9f2a738dc2b785dcfe06"
    end
  end

  # No zap stanza required
end
