# This file was generated by GoReleaser. DO NOT EDIT.
cask "javascript-package-delegator" do
  desc "A tool to delegate package installation to JavaScript package managers."
  homepage "https://github.com/louiss0/javascript-package-delegator"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jpd"

  on_macos do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_darwin_amd64.tar.gz"
      sha256 "3e7f4aad1327229fb28e1e0e985dc2c7b091298d82b9223a518723119bf1c5e4"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_darwin_arm64.tar.gz"
      sha256 "72937644dc65d742aa50757d3be99846d0ac03c1d3245d17cb981e1a1c0a70af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_linux_amd64.tar.gz"
      sha256 "da21a0a202909e1b0589ad28d5d8d00aac19bcecc8d48b6e59a0812ae20cb1ed"
    end
    on_arm do
      url "https://github.com/louiss0/javascript-package-delegator/releases/download/v1.1.0/javascript-package-delegator_1.1.0_linux_arm64.tar.gz"
      sha256 "a19dbd76f705dbea51d792cc528374e4265249e4b8fb970830778f75dca5aa61"
    end
  end

  # No zap stanza required
end
