name: Brew Audit

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ github.token }}

      - name: Homebrew diagnostics
        run: |
          brew --version
          brew config

      - name: Link current checkout as tap
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          set -euxo pipefail
          TAP_USER="${GITHUB_REPOSITORY_OWNER}"
          TAP_REPO="$(basename "${GITHUB_REPOSITORY}")"
          TAP_SHORT="${TAP_REPO#homebrew-}"
          BREW_TAPS_DIR="$(brew --repo)/Library/Taps/${TAP_USER}"

          mkdir -p "${BREW_TAPS_DIR}"
          ln -sfn "$GITHUB_WORKSPACE" "${BREW_TAPS_DIR}/${TAP_REPO}"

          # Tell Homebrew about the tap using canonical name (user/short)
          brew tap "${TAP_USER}/${TAP_SHORT}" || true
          
          # Basic tap verification
          brew tap-info "${TAP_USER}/${TAP_SHORT}"

      - name: Style check
        run: |
          brew style --display-cop-names Casks/*.rb

      - name: Validate cask syntax
        run: |
          # Test if cask can be loaded (basic syntax check)
          ruby -c Casks/javascript-package-delegator.rb

      - name: Audit casks (strict + online)
        run: |
          set -euxo pipefail
          TAP_USER="${{ github.repository_owner }}"
          TAP_REPO="$(basename "${{ github.repository }}")"
          TAP_SHORT="${TAP_REPO#homebrew-}"
          brew audit --cask --strict --online --tap="${TAP_USER}/${TAP_SHORT}"
