name: Brew Style Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  style-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ github.token }}

      - name: Style check
        run: |
          brew style --display-cop-names Casks/*.rb

      - name: Validate cask syntax
        run: |
          # Test if cask can be loaded (basic syntax check)
          ruby -c Casks/javascript-package-delegator.rb
